apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.general.app.name }}
  namespace: {{ $.Values.general.app.namespace }}
spec:
  selector:
    app: {{ $.Values.general.app.name }}
  ports:
    - protocol: TCP
      port: {{ $.Values.general.app.port }}
      targetPort: {{ $.Values.general.app.containerPort }}
  type: ClusterIP