general:
  api:
    name: simple-api
    externalName: simple-api-external
    namespace: api
    port: 80

ingress:
  name: kong-ingress
  namespace: gateway
  class: kong
  plugins:
    - request-transformer
    - response-transformer
    - redirect-api
config:
  name: kong-plugin-redirect-api
  pluginName: redirect-api
  path: customPlugins/redirect/**

kong:
  env:
    KONG_PLUGINS: "bundled,redirect-api"
    log_level: "debug"
  plugins:
    configMaps:
    - name: kong-plugin-redirect-api
      pluginName: redirect-api