apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.general.api.externalName }}
  namespace: {{ $.Values.ingress.namespace }}
spec:
  type: ExternalName
  externalName: {{ $.Values.general.api.name }}.{{ $.Values.general.api.namespace }}
  ports:
    - port: {{ $.Values.general.api.port }}
